/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;

import lombok.extern.slf4j.Slf4j;

@SpringBootApplication
@Slf4j
public class App implements CommandLineRunner{
    protected static Logger logger = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        new SpringApplicationBuilder(App.class).run(args);
    }

	@Override
	public void run(String... args) throws Exception {
        logger.debug("Hello World!!");
	}
}
